export const enum PageSegmentationMethod {
  ORIENTATION_AND_SCRIPT_DETECTION_ONLY = 0,
  AUTO_PAGE_SEGMENTATION_WITH_OSD = 1,
  AUTO_PAGE_SEGMENTATION_WITHOUT_OSD_AND_OCR = 2,
  AUTO_PAGE_SEGMENTATION_WITHOUT_OSD = 3,
  SINGLE_COLUMN_VARIABLE_SIZE = 4,
  SINGLE_UNIFORM_BLOCK_VERTICAL_TEXT = 5,
  SINGLE_UNIFORM_BLOCK_TEXT = 6,
  SINGLE_LINE = 7,
  SINGLE_WORD = 8,
  SINGLE_WORD_IN_CIRCLE = 9,
  SINGLE_CHAR = 10,
  SPARSE_TEXT = 11,
  SPARSE_TEXT_WITH_OSD = 12,
  RAW_SINGLE_LINE = 13,
}

export const enum OCREngineMode {
  TESSERACT = 0,
  LSTM = 1,
  TESSERACT_WITH_LSTM = 2,
  AUTO = 3,
}
